algoritmo "ParOuImpar"
//Algoritmo para informar se um número é par ou ímpar
var
   Num:inteiro
inicio
      Escreva("Digite um número: ")
      leia(Num)
      Se (Num%2=0)entao
         Escreva("O número digitado ",Num," é PAR!")
      Senao
           Escreva("O número digitado ",Num," é ÍMPAR!")
      FimSe
fimalgoritmo

//Nessa aula também foi apresentado que o comando Shift+G realiza o indentamento do código no visualg
