algoritmo "contmax"
//Contar até onde o usuário quiser, com a quantidade de saltos ele querer
var
   cont,valor,salt:inteiro
inicio
      cont<-0
      escreva("Deseja contar até quanto? ")
      leia (valor)
      escreva("Deseja saltar quantos números na contagem? ")
      leia (salt)
      enquanto (cont<=valor)faca
        escreval (cont)
        cont<-cont+salt
      fimenquanto
      Escreva("terminei de contar!")
fimalgoritmo
               

      
